# Generated by Django 5.0 on 2024-12-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='photo',
        ),
    ]
