# Generated by Django 5.0 on 2024-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_number', models.IntegerField(unique=True)),
                ('autonomy_level', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], max_length=20)),
                ('extended_vacation', models.BooleanField(default=False)),
                ('grade', models.CharField(choices=[('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Séptimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Décimo'), ('once', 'Once')], max_length=20)),
            ],
        ),
    ]
