# Generated by Django 5.0 on 2024-12-13 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop'),
        ),
    ]
