# Generated by Django 5.0 on 2025-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rotation_workshop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
