# Generated by Django 5.0 on 2024-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(default='0'),
        ),
    ]
