# Generated by Django 5.0 on 2024-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_block_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(default='primary', max_length=20),
        ),
    ]
