# Generated by Django 5.0 on 2024-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_name_alter_workshop_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='max_capacity',
            field=models.IntegerField(default=25),
        ),
    ]
