# Generated by Django 5.0 on 2024-12-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='high_school',
        ),
    ]
