# Generated by Django 5.0 on 2024-12-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_remove_block_high_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('primary', 'Primaria'), ('high_school', 'Bachillerato'), ('collective', 'Colectivo')], default='primary', max_length=20),
        ),
    ]
