# Generated by Django 5.0 on 2024-12-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('workshops', '0005_workshop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
