# Generated by Django 5.0 on 2025-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_workshop_max_capacity_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('preschool', 'Preescolar'), ('primary', 'Primaria'), ('high_school', 'Bachillerato'), ('collective', 'Colectivo')], default='primary', max_length=20),
        ),
    ]
