# Generated by Django 5.0 on 2025-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_alter_workshop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_capacity_aux_preschool',
            field=models.IntegerField(blank=True, help_text='Capacidad bloques Bachillerato (solo en colectivos)', null=True),
        ),
    ]
