# Generated by Django 5.0 on 2024-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('neutral', 'No llamado')], default='neutral', max_length=10),
        ),
    ]
