# Generated by Django 5.0 on 2025-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_rotation_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='general_data',
            field=models.TextField(blank=True, help_text='Información adicional del estudiante', null=True, verbose_name='Datos Generales'),
        ),
    ]
