# Generated by Django 5.0 on 2024-12-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('workshops', '0003_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='students.student'),
        ),
    ]
