# Generated by Django 5.0 on 2025-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_workshop_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_capacity_aux',
            field=models.IntegerField(blank=True, help_text='Capacidad bloques Bachillerato (solo en colectivos)', null=True),
        ),
    ]
